apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: app-namespace
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: grafana-pv     
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard 