apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: app-namespace
  labels:
    app: grafana
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: grafana
  type: NodePort 