apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app-namespace
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http
      port: 5174
      targetPort: 5174
      protocol: TCP