apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage-pvc
  namespace: app-namespace
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: prometheus-pv
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard 