apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: app-namespace
  labels:
    app: prometheus
spec:
  ports:
  - port: 9090
    targetPort: web
    protocol: TCP
    name: http
  selector:
    app: prometheus
  type: ClusterIP 